package com.wrriormedia.app.common;


public class ConstantSet {

    //页面跳转参数key

    public static final String KEY_GLOBAL_CONFIG_FILENAME = "KEY_GLOBAL_CONFIG_FILENAME";
    public static final String KEY_GLOBAL_DOWNLOAD_APP = "KEY_GLOBAL_DOWNLOAD_APP";
    public static final int PAGE_SIZE = 20;

    public static final String KEY_IS_AD_ACTIVITY = "KEY_IS_AD_ACTIVITY";
    public static final String KEY_IS_TEXT_AD_ACTIVITY = "KEY_IS_TEXT_AD_ACTIVITY";
    public static final String KEY_IS_LOCK_SCREEN = "KEY_IS_LOCK_SCREEN";
    public static final String KEY_LOG_TIME = "KEY_LOG_TIME";

    // EventBus action
    public static final String KEY_EVENT_ACTION_PLAY_VIDEO = "KEY_EVENT_ACTION_PLAY_VIDEO";
    public static final String KEY_EVENT_ACTION_PLAY_IMAGE = "KEY_EVENT_ACTION_PLAY_IMAGE";
    public static final String KEY_EVENT_ACTION_PLAY_TEXT = "KEY_EVENT_ACTION_PLAY_TEXT";
    public static final String KEY_EVENT_ACTION_PLAY_NEXT = "KEY_EVENT_ACTION_PLAY_NEXT";
    public static final String KEY_EVENT_ACTION_PLAY_TEXT_NEXT = "KEY_EVENT_ACTION_PLAY_TEXT_NEXT";
    public static final String KEY_EVENT_ACTION_PLAY_NO_AD = "KEY_EVENT_ACTION_PLAY_NO_AD";
    public static final String KEY_EVENT_ACTION_PLAY_NO_TEXT_AD = "KEY_EVENT_ACTION_PLAY_NO_TEXT_AD";

    public static final String KEY_EVENT_ACTION_LOG_TIMER = "KEY_EVENT_ACTION_LOG_TIMER";
    public static final String KEY_EVENT_ACTION_LOADER_IMAGE = "KEY_EVENT_ACTION_LOADER_IMAGE";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_IMAGE = "KEY_EVENT_ACTION_DOWNLOAD_IMAGE";

    public static final String KEY_EVENT_ACTION_LOCK_SCREEN = "KEY_EVENT_ACTION_LOCK_SCREEN";
    public static final String KEY_EVENT_ACTION_PAUSE_PLAY = "KEY_EVENT_ACTION_PAUSE_PLAY";
    public static final String KEY_EVENT_ACTION_RESTART_PLAY = "KEY_EVENT_ACTION_RESTART_PLAY";

    //推送action
    public static final String KEY_EVENT_ACTION_NEW_VERSION = "KEY_EVENT_ACTION_NEW_VERSION";
    public static final String KEY_EVENT_ACTION_NEW_AD = "KEY_EVENT_ACTION_NEW_AD";
    public static final String KEY_EVENT_ACTION_NEW_TEXT_AD = "KEY_EVENT_ACTION_NEW_TEXT_AD";
    public static final String KEY_EVENT_ACTION_DELETE_AD = "KEY_EVENT_ACTION_DELETE_AD";
    public static final String KEY_EVENT_ACTION_SYS_STATUS = "KEY_EVENT_ACTION_SYS_STATUS";
    public static final String KEY_EVENT_ACTION_LOG_TIME = "KEY_EVENT_ACTION_LOG_TIME";
    public static final String KEY_EVENT_ACTION_BRITENESS = "KEY_EVENT_ACTION_BRITENESS";
    public static final String KEY_EVENT_ACTION_VOLUME = "KEY_EVENT_ACTION_VOLUME";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_SHOW_START = "KEY_EVENT_ACTION_DOWNLOAD_SHOW_START";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_SHOW_FINISH = "KEY_EVENT_ACTION_DOWNLOAD_SHOW_FINISH";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_SHOW_FAILED = "KEY_EVENT_ACTION_DOWNLOAD_SHOW_FAILED";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_SHOW_NORMAL = "KEY_EVENT_ACTION_DOWNLOAD_SHOW_NORMAL";
    public static final String KEY_EVENT_ACTION_RESTART_PLAY_DOWNLOAD_APP_FAILED = "KEY_EVENT_ACTION_RESTART_PLAY_DOWNLOAD_APP_FAILED";

    //下载视频文件
    public static final String KEY_EVENT_ACTION_DOWNLOAD_STATUS_START = "KEY_EVENT_ACTION_DOWNLOAD_STATUS_START";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_STATUS_FINISH = "KEY_EVENT_ACTION_DOWNLOAD_STATUS_FINISH";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_STATUS_FAILED = "KEY_EVENT_ACTION_DOWNLOAD_STATUS_FAILED";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_STATUS_NORMAL = "KEY_EVENT_ACTION_DOWNLOAD_STATUS_NORMAL";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_NEXT = "KEY_EVENT_ACTION_DOWNLOAD_NEXT";

    // 下载app
    public static final String KEY_EVENT_ACTION_DOWNLOAD_APP_STATUS_NORMAL = "KEY_EVENT_ACTION_DOWNLOAD_APP_STATUS_NORMAL";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_APP_STATUS_FAILED = "KEY_EVENT_ACTION_DOWNLOAD_APP_STATUS_FAILED";
    public static final String KEY_EVENT_ACTION_DOWNLOAD_APP_STATUS_FINISH = "KEY_EVENT_ACTION_DOWNLOAD_APP_STATUS_FINISH";
}
